app:
  port: ':8000'

postgreSQL:
  username: 'postgres'
  host: 'db'
  port: '5432'
  database: 'postgres'
  sslmode: 'disable'
  password: 'qwerty'

auth:
  jwt:
    secret: 'sgkfdjgiodsio4wu59834ufhf2q4hvqh984phq43u'
    expire: 3600
    temporaryExpire: 600
  salt: 'kfainecuignyxwamg7nqoc8w7gnxrgnerkh'
  confirmationCode:
    expire: 3600


  awsAccessKeyId: 'awsAccessKeyId'
  awsSecretAccessKey: 'awsSecretAccessKey'
  awsRegion: 'awsRegion'
  awsBucketName: 'awsBucketName'

sendGrid:
  key: 'sendGridAccessKey'

twilio:
  accountSid: 'accountSid'
  authToken: 'authToken'
  from: 'from'

stripe:
  key: 'stripeKey'
  refreshURL: 'http://localhost:3000/login'
  returnURL: 'http://localhost:3000/obtain'
  loanID: 'loanID'
  repayLoanID: 'repayLoanID'
  paymentSuccessURL: 'http://localhost:3000/obtain?type=success'
  paymentCancelURL: 'http://localhost:3000/obtain?type=error'
  webhookKey: 'webhookKey'

