app:
  port: ":8000"

postgreSQL:
  username: "eliftechconsole"
  host: "localhost"
  port: "5432"
  database: "postgres"
  sslmode: "disable"
  password: "qwerty"

auth:
  jwt:
    secret: "sgkfdjgiodsio4wu59834ufhf2q4hvqh984phq43u"
    expire: 3600
    temporaryExpire: 600
  salt: "kfainecuignyxwamg7nqoc8w7gnxrgnerkh"
  confirmationCode:
    expire: 3600

awsS3:
  awsAccessKeyId: "AKIARAGU6ON46YN6DMLY"
  awsSecretAccessKey: "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"
  awsRegion: "us-west-2"
  awsBucketName: "test-3-2-3"

sendGrid:
  key: "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"

twilio:
  accountSid: "AC342c3eefb8bcfb092801f3065fc77eda"
  authToken: "fcf346001bab0bd822f9cd755b8902a2"
  from: "+19807058661"

stripe:
  key: "sk_test_51M6sLzBit1Xos21HJ6dSyhvXHJdmetDC7AjmNaKMmcrmvvCKT1ViE1opckQIBxVTHEaTI79tV8xoKxwOLppDTB4r00ZH0EjrZ6"
  refreshURL: "http://localhost:3000/login"
  returnURL: "http://localhost:3000/obtain"
  loanID: "prod_MqwYpexHoVQPGw"
  repayLoanID: "prod_MqwoPAJ55lfnQ9"
  paymentSuccessURL: "http://localhost:3000/investor/cabinet?type=success"
  paymentCancelURL: "http://localhost:3000/investor/cabinet?type=error"
  webhookKey: "whsec_8f989d759c48d2c9243d337fcd0eee3a604ff04c40604e2da4a46d0fde19a74a"
