app:
  port: ':8000'

postgreSQL:
  username: 'postgres'
  host: 'localhost'
  port: '5436'
  database: 'postgres'
  sslmode: 'disable'
  password: 'qwerty'

auth:
  jwt:
    secret: 'sgkfdjgiodsio4wu59834ufhf2q4hvqh984phq43u'
    expire: 3600
    temporaryExpire: 600
  salt: 'kfainecuignyxwamg7nqoc8w7gnxrgnerkh'
  confirmationCode:
    expire: 3600

awsS3:
  awsAccessKeyId: 'AKIARAGU6ON46YN6DMLY'
  awsSecretAccessKey: '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'
  awsRegion: 'us-west-2'
  awsBucketName: 'test-3-2-3'

sendGrid:
  key: 'sendGridAccessKey'

twilio:
  accountSid: 'accountSid'
  authToken: 'authToken'
  from: 'from'

stripe:
  key: 'sk_test_51M6sLzBit1Xos21HJ6dSyhvXHJdmetDC7AjmNaKMmcrmvvCKT1ViE1opckQIBxVTHEaTI79tV8xoKxwOLppDTB4r00ZH0EjrZ6'
  refreshURL: 'http://localhost:3000/refresh'
  returnURL: 'http://localhost:3000/obtain'
  loanID: 'prod_LzpkhourSVjDcM'
  repayLoanID: 'prod_Lzpl1uJVi6qGVf'
  paymentSuccessURL: 'http://localhost:3000/success'
  paymentCancelURL: 'http://localhost:3000/cancel'
  webhookKey: 'whsec_8f989d759c48d2c9243d337fcd0eee3a604ff04c40604e2da4a46d0fde19a74a'
