version: '3.9'
services:
  back:
    restart: always
    build: ./
    command: ./back
    depends_on:
      - db
    ports:
      - '8000:8000'
  db:
    restart: always
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'
