import { IInvestment } from '@/models/investment.interface';

export const LoanList: IInvestment[] = [
  {
    key: '1',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc: 'Треба  купити  морозильник до літа....',
    creditTerm: 24,
    creditRate: 12,
    creditEstimate: 60,
    creditAction: 'Докладніше',
  },
  {
    key: '2',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc: 'Треба  купити  морозильник до літа....',
    creditTerm: 12,
    creditRate: 12,
    creditEstimate: 100,
    creditAction: 'Докладніше',
  },
  {
    key: '3',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
  {
    key: '4',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 12,
    creditRate: 12,
    creditEstimate: 100,
    creditAction: 'Докладніше',
  },
  {
    key: '5',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 12,
    creditRate: 12,
    creditEstimate: 40,
  },
  {
    key: '6',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 12,
    creditRate: 12,
    creditEstimate: 100,
  },
  {
    key: '7',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
  {
    key: '8',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
  {
    key: '9',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
  {
    key: '10',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 40,
  },
  {
    key: '11',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
  {
    key: '12',
    creditSum: 10000,
    creditTitle: 'Морозильник в каярню',
    creditDesc:
      'Треба  купити  морозильник до літа.Треба  купити  морозильник до літа.',
    creditTerm: 18,
    creditRate: 12,
    creditEstimate: 70,
  },
];

export const offersOffline = [
  {
    key: '1',
    CreditTitle: "Кав'ярня",
    CreditSum: 232323,
    CreditRate: 3,
    CreditNewRate: 5,
    CreditTerm: 12,
    CreditNewTerm: 14,
    TotalSum: 252555,
    TotalNewSum: 343434,
    MonthlyPayment: 564.54,
    NewMonthlyPayment: 568.56,
  },
  {
    key: '2',
    CreditTitle: 'Пекарня',
    CreditSum: 54545,
    CreditRate: 6,
    CreditNewRate: 13,
    CreditTerm: 24,
    CreditNewTerm: 18,
    TotalSum: 252555,
    TotalNewSum: 343434,
    MonthlyPayment: 564.54,
    NewMonthlyPayment: 568.56,
  },
  {
    key: '4',
    CreditTitle: 'Магазин',
    CreditSum: 77777,
    CreditRate: 3,
    CreditNewRate: 5,
    CreditTerm: 13,
    CreditNewTerm: 12,
    TotalSum: 252555,
    TotalNewSum: 343434,
    MonthlyPayment: 564.54,
    NewMonthlyPayment: 568.56,
  },
  {
    key: '4',
    CreditTitle: 'Аптека',
    CreditSum: 9999,
    CreditRate: 3,
    CreditNewRate: 6,
    CreditTerm: 8,
    CreditNewTerm: 18,
    TotalSum: 252555,
    TotalNewSum: 343434,
    MonthlyPayment: 564.54,
    NewMonthlyPayment: 568.56,
  },
];
